version: '2'

services:
  server:
    image: nginx:latest
    ports:
        - "8082:80"
    volumes:
      - code:/var/www/html
      - nginx-confd:/etc/nginx/conf.d/

  php:    
    image: marcelofmatos/leegui
    volumes:
      - code:/var/www/html
      
  init:
    image: marcelofmatos/leegui
    command: init.sh
    restart: "no"
    volumes:
      - code:/app

volumes:
  code:
    driver: local
  nginx-confd:
    driver: local
