version: '2'

services:
  server:
    image: nginx:latest
    ports:
        - "8082:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf

  php:    
    image: marcelofmatos/leegui
    volumes:
      - code:/var/www/html
      
  init:
    image: composer
    command: composer install
    restart: "no"
    volumes:
      - code:/app
      
volumes:
  code:
    driver: local
  nginx-confd:
    driver: local
