name: Code Quality

on:
  pull_request:
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'

jobs:
  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest
    container:
      image: php:7.4-cli
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y git unzip
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer
        composer install --prefer-dist --no-progress
        composer require --dev phpstan/phpstan
    
    - name: Run PHPStan
      run: vendor/bin/phpstan analyse app --level=5 --no-progress

  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    container:
      image: php:7.4-cli
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install PHP CS Fixer
      run: |
        curl -L https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v3.13.0/php-cs-fixer.phar -o php-cs-fixer
        chmod +x php-cs-fixer
    
    - name: Run PHP CS Fixer
      run: ./php-cs-fixer fix --dry-run --diff --verbose
